debug: false
spring:
  redis:
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: Mysql666..
  servlet:
    #上传文件限制
    multipart:
      max-file-size: 64000MB
      max-request-size: 6400MB
  datasource:
    username: root
    password: Mysql666..
    url: jdbc:mysql://127.0.0.1:3306/template?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: file:./data
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 20008
  servlet:
    context-path: /
##swagger 配置
knife4j:
  enable: true
  setting:
    language: zh-CN
  basic:
    enable: false
    username: admin
    password: qq

logging:
  level:
    root: info
    com.template.mapper: info
  file:
    path: spring.log

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: simple-uuid
  # 是否输出操作日志
  is-log: false
  #是否从header读取token
  isReadHeader: true
  #是否从body里读取token
  isReadBody: false
  #是否从cookie里读取token
  isReadCookie: false
  #登录成功返回是否写入token
  isWriteHeader: true